# Generated by Django 4.1.3 on 2022-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_ended',
            field=models.DateTimeField(help_text='Time should be formatted as DD-MM-YYYY H:M:S', verbose_name='Date and Time ended'),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_started',
            field=models.DateTimeField(help_text='Time should be formatted as DD-MM-YYYY H:M:S', verbose_name='Date and Time started'),
        ),
    ]
