# Generated by Django 4.1.3 on 2022-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_log_time_ended_alter_log_time_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
